"""Spanish translations for Piklin, kept as data and written to po/es.po.

Run: python3 po/es_catalog.py   (regenerates po/es.po from po/piklin.pot)

Voice: "tú", plain words, short. Terms: Biblioteca, Álbum, Carpeta,
Favoritos, Eliminados recientemente, Copia de seguridad, Estilos.
A plural entry is a tuple (singular, plural).
"""
ES = {
    # -- preferences tabs: kept short so they fit side by side ------------------
    "preferences tab\x04General": "General",
    "preferences tab\x04Storage": "Espacio",
    "preferences tab\x04Backup": "Copias",
    "preferences tab\x04Library": "Carpetas",

    # -- automatic backup -------------------------------------------------------
    "Connecting to {name}…": "Conectando con {name}…",
    "Backing up to {name} — {done} of {total}": "Copiando a {name} — {done} de {total}",
    "Backing up to {name} — {done} of {total} ({percent}%)": "Copiando a {name} — {done} de {total} ({percent}%)",
    "{count} file couldn't be uploaded": ("{count} archivo no se pudo subir", "{count} archivos no se pudieron subir"),
    "just now": "hace un momento",
    "{count} minute ago": ("hace {count} minuto", "hace {count} minutos"),
    "today at {time}": "hoy a las {time}",
    "yesterday at {time}": "ayer a las {time}",
    "Backing up…": "Haciendo la copia…",
    "Automatic backup is off": "La copia automática está apagada",
    "Backup waits until battery saver is off": "La copia espera a que se apague el ahorro de batería",
    "Can't reach {name}, will try again": "No se puede conectar con {name}, se volverá a intentar",
    "Backup waits for a connection": "La copia espera a que haya conexión",
    "Backup stopped: {problem}": "La copia se detuvo: {problem}",
    "Changes waiting to back up": "Hay cambios pendientes de copiar",
    "Backed up {when}": "Copia hecha {when}",
    "Not backed up yet": "Todavía sin copia",

    # -- smart album conditions -----------------------------------------------
    "Filename": "Nombre del archivo",
    "Folder path": "Ruta de la carpeta",
    "Camera make": "Marca de la cámara",
    "Camera model": "Modelo de la cámara",
    "Lens": "Objetivo",
    "Rating": "Valoración",
    "Aperture (f/)": "Apertura (f/)",
    "Focal length": "Distancia focal",
    "Width": "Ancho",
    "Height": "Alto",
    "File size": "Tamaño del archivo",
    "Favourite": "Favorito",
    "Edited": "Editadas",
    "Has location": "Tiene ubicación",
    "Date taken": "Fecha de la foto",
    "File type": "Tipo de archivo",
    "Media type": "Tipo",
    "Video length (seconds)": "Duración del video (segundos)",
    "is": "es",
    "is not": "no es",
    "contains": "contiene",
    "does not contain": "no contiene",
    "greater than": "mayor que",
    "less than": "menor que",
    "is true": "sí",
    "is false": "no",
    "in the last days": "en los últimos días",
    "before": "antes de",
    "after": "después de",
    "is video": "es un video",
    "is photo": "es una foto",

    # -- storing and exporting photos -------------------------------------------
    "Original": "Original",
    "Keeps your files exactly as they are.": "Deja tus archivos tal como están.",
    "Exact Picture, Smaller File": "Misma imagen, archivo más pequeño",
    "Exactly the same picture in a smaller file. Saves the most on screenshots.":
        "Exactamente la misma imagen en un archivo más pequeño. Ahorra más en capturas de pantalla.",
    "Looks the Same": "Se ve igual",
    "Much smaller files that look the same to the eye. Usually about half the size.":
        "Archivos mucho más pequeños que a simple vista se ven igual. Suelen ocupar la mitad.",
    "Balanced": "Equilibrado",
    "A little softer if you look very closely, and clearly smaller. Good for big libraries.":
        "Un poco más suave si miras muy de cerca, y bastante más pequeño. Bueno para bibliotecas grandes.",
    "Space Saver": "Ahorro de espacio",
    "Still looks good, at about a quarter of the original size.":
        "Sigue viéndose bien, con una cuarta parte del tamaño original.",
    "Smallest Files": "Archivos mínimos",
    "As small as possible. Photos are made smaller too, so it's good for keeping but not for printing.":
        "Lo más pequeño posible. También reduce las fotos, así que sirve para guardar pero no para imprimir.",
    "kept as-is": "se deja tal cual",
    "can't read the file ({error})": "no se puede leer el archivo ({error})",
    "lossless would be larger; original kept": "sin pérdida ocuparía más; se deja el original",
    "no ladder step met the target; used highest quality": "no se alcanzó el objetivo; se usó la máxima calidad",
    "couldn't save the file ({error})": "no se pudo guardar el archivo ({error})",
    "already well compressed; original kept": "ya estaba bien comprimido; se deja el original",
    "made smaller, up to {size} px on the long side": "reducido a {size} px como máximo en el lado largo",
    "copied unchanged": "copiado sin cambios",
    "original was already smaller; copied unchanged": "el original ya era más pequeño; copiado sin cambios",

    # -- devices -----------------------------------------------------------------
    "Camera": "Cámara",
    "USB Drive": "Unidad USB",

    # -- Looks ---------------------------------------------------------------------
    "Portrait": "Retrato",
    "Smooth": "Suave",
    "Pop": "Intenso",
    "Accentuate": "Realzar",
    "Faded Glow": "Brillo desvaído",
    "Morning": "Mañana",
    "Bright": "Luminoso",
    "Fine Art": "Artístico",
    "Yellow": "Amarillo",
    "Film": "Película",
    "Push": "Forzado",
    "Drama 1": "Drama 1",
    "Structure": "Estructura",
    "Silhouette": "Silueta",
    "Bright Spark": "Destello",
    "Warm Film": "Película cálida",
    "Noir Classic": "Noir clásico",
    "Faded Vintage": "Vintage desvaído",
    "Cold Steel": "Acero frío",
    "Golden Hour": "Hora dorada",
    "High Key": "Clave alta",

    # -- editing tools ---------------------------------------------------------------
    "Tune Image": "Ajustar imagen",
    "Adjust": "Ajustes",
    "Adjust brightness, contrast, color and more.": "Ajusta el brillo, el contraste, el color y más.",
    "Brightness": "Brillo",
    "Contrast": "Contraste",
    "Saturation": "Saturación",
    "Ambiance": "Ambiente",
    "Highlights": "Iluminaciones",
    "Shadows": "Sombras",
    "Warmth": "Calidez",
    "Details": "Detalles",
    "Bring out texture and make the photo sharper.": "Resalta la textura y hace la foto más nítida.",
    "Sharpening": "Nitidez",
    "Neutral": "Neutro",
    "Soft Contrast": "Contraste suave",
    "Hard Contrast": "Contraste fuerte",
    "Dark": "Oscuro",
    "Faded": "Desvaído",
    "Matte": "Mate",
    "Lift Shadows": "Aclarar sombras",
    "Crush Blacks": "Negros profundos",
    "Curves": "Curvas",
    "Fine-tune light and color with curves.": "Afina la luz y el color con curvas.",
    "Preset": "Predefinido",
    "White Balance": "Balance de blancos",
    "Make colors warmer or cooler, or fix a color cast.": "Haz los colores más cálidos o fríos, o corrige un tono raro.",
    "Temperature": "Temperatura",
    "Tint": "Matiz",
    "Pick something gray": "Elige algo gris",
    "Tonal Contrast": "Contraste tonal",
    "Effects": "Efectos",
    "Add punch to the dark, middle and bright parts separately.":
        "Da más fuerza a las zonas oscuras, medias y claras por separado.",
    "High Tones": "Tonos altos",
    "Mid Tones": "Tonos medios",
    "Low Tones": "Tonos bajos",
    "Protect Shadows": "Proteger sombras",
    "Protect Highlights": "Proteger luces",
    "Style": "Estilo",
    "Nature": "Naturaleza",
    "People": "Personas",
    "Fine": "Fino",
    "Strong": "Fuerte",
    "HDR Scape": "Paisaje HDR",
    "Bring out detail in both bright and dark areas.": "Resalta el detalle en las zonas claras y oscuras.",
    "Filter Strength": "Intensidad del filtro",
    "Smoothing": "Suavizado",
    "Glamour Glow": "Brillo glamuroso",
    "Add a soft, dreamy glow.": "Añade un brillo suave y soñador.",
    "Glow": "Brillo",
    "Drama 2": "Drama 2",
    "Bright 1": "Luminoso 1",
    "Bright 2": "Luminoso 2",
    "Dark 1": "Oscuro 1",
    "Dark 2": "Oscuro 2",
    "Drama": "Drama",
    "A bold, moody look with strong detail.": "Un aspecto intenso y dramático con mucho detalle.",
    "Vignette": "Viñeta",
    "Darken or brighten the edges of the photo.": "Oscurece o aclara los bordes de la foto.",
    "Outer Brightness": "Brillo exterior",
    "Inner Brightness": "Brillo interior",
    "Size": "Tamaño",
    "Center": "Centro",
    "Red": "Rojo",
    "Orange": "Naranja",
    "Green": "Verde",
    "Blue": "Azul",
    "Vintage": "Vintage",
    "Looks": "Estilos",
    "Old-photo color styles.": "Colores de fotos antiguas.",
    "Style Strength": "Intensidad del estilo",
    "Center Focus": "Enfoque central",
    "Vignette Strength": "Intensidad de la viñeta",
    "Grainy Film": "Película granulada",
    "Film looks with grain.": "Aspectos de película con grano.",
    "Grain": "Grano",
    "Retrolux": "Retrolux",
    "Retro looks with scratches and light leaks.": "Aspectos retro con rayas y fugas de luz.",
    "Scratches": "Rayas",
    "Light Leaks": "Fugas de luz",
    "Blur": "Desenfoque",
    "Grunge": "Grunge",
    "Rough, textured looks.": "Aspectos ásperos y con textura.",
    "Texture Strength": "Intensidad de la textura",
    "Black & White": "Blanco y negro",
    "Turn the photo black and white.": "Pasa la foto a blanco y negro.",
    "Color Filter": "Filtro de color",
    "Noir": "Noir",
    "A dark, classic black and white look.": "Un blanco y negro oscuro y clásico.",
    "Wash": "Lavado",
    "Lens Blur": "Desenfoque de lente",
    "Blur the background so your subject stands out.": "Desenfoca el fondo para que resalte lo importante.",
    "Blur Strength": "Intensidad del desenfoque",
    "Transition": "Transición",
    "Shape": "Forma",
    "Circle": "Círculo",
    "Planar": "Lineal",
    "Free": "Libre",
    "Square": "Cuadrado",
    "Golden": "Proporción áurea",
    "Crop": "Recortar",
    "Geometry": "Geometría",
    "Cut the photo to a new shape.": "Recorta la foto a otra forma.",
    "Rectangle": "Rectángulo",
    "Aspect": "Proporción",
    "Rotate": "Girar",
    "Turn, straighten or mirror the photo.": "Gira, endereza o refleja la foto.",
    "Straighten": "Enderezar",
    "Mirror": "Reflejar",
    "Flip": "Voltear",
    "Perspective": "Perspectiva",
    "Straighten buildings and tilted lines.": "Endereza edificios y líneas inclinadas.",
    "Tilt Horizontal": "Inclinación horizontal",
    "Tilt Vertical": "Inclinación vertical",
    "Scale": "Escala",
    "Fill": "Relleno",
    "Smart": "Inteligente",
    "White": "Blanco",
    "Black": "Negro",
    "Expand": "Expandir",
    "Add space around the photo.": "Añade espacio alrededor de la foto.",
    "Amount": "Cantidad",
    "Sides": "Lados",
    "All": "Todos",
    "Horizontal": "Horizontal",
    "Vertical": "Vertical",
    "Selective": "Selectivo",
    "Local": "Local",
    "Change light or color in just one area.": "Cambia la luz o el color solo en una zona.",
    "Points": "Puntos",
    "Dodge & Burn": "Aclarar y oscurecer",
    "Exposure": "Exposición",
    "Brush": "Pincel",
    "Paint light, darkness or color onto parts of the photo.": "Pinta luz, sombra o color en partes de la foto.",
    "Strokes": "Trazos",
    "Healing": "Corrector",
    "Remove spots and small objects.": "Quita manchas y objetos pequeños.",
    "Spotlight": "Foco",
    "Fair": "Claro",
    "Even": "Uniforme",
    "Warm": "Cálido",
    "Brighten faces, smooth skin and sharpen eyes. Done on this computer.":
        "Ilumina caras, suaviza la piel y aviva los ojos. Se hace en este ordenador.",
    "Face Spotlight": "Luz en la cara",
    "Skin Smoothing": "Suavizar piel",
    "Eye Clarity": "Claridad de ojos",
    "Head Pose": "Postura de la cabeza",
    "Gently turn a face or add a smile. Keep it subtle.": "Gira un poco la cara o añade una sonrisa. Mejor con suavidad.",
    "Up / Down": "Arriba / abajo",
    "Left / Right": "Izquierda / derecha",
    "Tilt": "Inclinación",
    "Smile": "Sonrisa",
    "Eye Emphasis": "Realzar ojos",
    "Double Exposure": "Doble exposición",
    "Blend another photo into this one.": "Mezcla otra foto con esta.",
    "Image": "Imagen",
    "Blend Mode": "Modo de mezcla",
    "Opacity": "Opacidad",
    "Desaturate": "Desaturar",
    "Plain": "Sencillo",
    "Bold": "Negrita",
    "Banner": "Pancarta",
    "Outline": "Contorno",
    "Caption": "Pie de foto",
    "Spaced": "Espaciado",
    "Text": "Texto",
    "Overlay": "Superposición",
    "Add text to the photo.": "Añade texto a la foto.",
    "Rotation": "Giro",
    "Color": "Color",
    "Position": "Posición",
    "None": "Ninguno",
    "Cream": "Crema",
    "Charcoal": "Carbón",
    "Museum": "Museo",
    "Polaroid": "Polaroid",
    "Film Edge": "Borde de película",
    "Torn": "Rasgado",
    "Frames": "Marcos",
    "Add a border.": "Añade un borde.",

    # -- dates ---------------------------------------------------------------------
    "January": "enero", "February": "febrero", "March": "marzo", "April": "abril",
    "May": "mayo", "June": "junio", "July": "julio", "August": "agosto",
    "September": "septiembre", "October": "octubre", "November": "noviembre",
    "December": "diciembre",
    "Monday": "lunes", "Tuesday": "martes", "Wednesday": "miércoles", "Thursday": "jueves",
    "Friday": "viernes", "Saturday": "sábado", "Sunday": "domingo",
    "{month} {year}": "{month} de {year}",
    "{weekday}, {day} {month} {year}": "{weekday}, {day} de {month} de {year}",
    "{day} {month}": "{day} de {month}",
    "Match the computer": "Igual que el ordenador",

    # -- renaming --------------------------------------------------------------------
    "The name can't be empty.": "El nombre no puede estar vacío.",
    "A file name can't contain {characters}": "Un nombre de archivo no puede contener {characters}",
    "A name starting with a dot would hide the photo.": "Un nombre que empieza con punto ocultaría la foto.",
    "That name is too long.": "Ese nombre es demasiado largo.",
    "That photo is no longer in the library.": "Esa foto ya no está en la biblioteca.",
    "“{name}” isn't on this computer. Is its drive connected?": "“{name}” no está en este ordenador. ¿Está conectada su unidad?",
    "There is already a file named “{name}” in that folder.": "Ya hay un archivo llamado “{name}” en esa carpeta.",
    "“{name}” is already in the library.": "“{name}” ya está en la biblioteca.",
    "This folder can't be changed: “{folder}”.": "Esta carpeta no se puede modificar: “{folder}”.",
    "The file couldn't be renamed: {error}.": "No se pudo cambiar el nombre del archivo: {error}.",
    "The library couldn't be updated, so the file keeps its old name.":
        "No se pudo actualizar la biblioteca, así que el archivo mantiene su nombre anterior.",

    # -- backup destinations ------------------------------------------------------------
    "Couldn't show the folders": "No se pudieron mostrar las carpetas",
    "Couldn't read the backup destination: {error}": "No se pudo leer el destino de la copia: {error}",
    "The file couldn't be uploaded": ("El archivo no se pudo subir", "No se pudo subir ninguno de los {count} archivos"),
    "Couldn't read the backup: {error}": "No se pudo leer la copia: {error}",
    "The file couldn't be restored": ("El archivo no se pudo recuperar", "No se pudo recuperar ninguno de los {count} archivos"),
    "No folder chosen": "No se eligió ninguna carpeta",
    "This folder can't be found": "No se encuentra esta carpeta",
    "Not a folder": "No es una carpeta",
    "Piklin can't save files in this folder": "Piklin no puede guardar archivos en esta carpeta",
    "Connected": "Conectado",
    "Enter the server address": "Escribe la dirección del servidor",
    "The address must start with https:// or http://": "La dirección tiene que empezar con https:// o http://",
    "http:// only works at home": "http:// solo funciona en casa",
    "Use https:// for a server on the internet, so your password stays private":
        "Usa https:// para un servidor en internet, así tu contraseña queda protegida",
    "No password saved": "No hay contraseña guardada",
    "The keyring is still locked": "El llavero de contraseñas aún está bloqueado",
    "Activity Log": "Registro de actividad",
    "A new version of Piklin is available": "Hay una versión nueva de Piklin",
    "Update Available": "Actualización disponible",
    "Would you like to update Piklin?": "¿Quieres actualizar Piklin?",
    "You have": "Tienes",
    "You would get": "Tendrías",
    "build {build}": "compilación {build}",
    "The same version with fixes, published again.": "La misma versión con arreglos, publicada de nuevo.",
    "What's new in {version}": "Novedades de la {version}",
    "Improvements and fixes.": "Mejoras y arreglos.",
    "You can update later with Update Available, in the sidebar.":
        "Puedes actualizar más tarde con Actualización disponible, en la barra lateral.",
    "Install Now": "Instalar ahora",
    "Installing Piklin {version}…": "Instalando Piklin {version}…",
    "Please keep Piklin open. It reopens by itself when it is done.":
        "Deja Piklin abierto. Se vuelve a abrir solo cuando termina.",
    "Piklin {version} is installed": "Piklin {version} está instalado",
    "Piklin will reopen in a moment.": "Piklin se volverá a abrir en un momento.",
    "The update couldn't be installed": "No se pudo instalar la actualización",
    "Try again, or download it from the website.": "Inténtalo de nuevo o descárgala desde la página web.",
    "Try Again": "Reintentar",
    "Check for updates": "Buscar actualizaciones",
    "When Piklin opens, and every hour while it is open, Piklin asks GitHub whether a new version is out and lets you choose whether to install it. Nothing is installed without asking. Nothing about you or your photos is sent.":
        "Al abrirse, y cada hora mientras está abierto, Piklin pregunta a GitHub si hay una versión nueva y te deja elegir si instalarla. Nunca se instala nada sin preguntarte. No se envía nada sobre ti ni tus fotos.",
    "Accept": "Aceptar",
    "Close": "Cerrar",
    "Installs the update and reopens Piklin": "Instala la actualización y vuelve a abrir Piklin",
    "Opens the download page": "Abre la página de descarga",
    "You can update whenever you like with Update Available, at the bottom of the sidebar.":
        "Puedes actualizar cuando quieras con Actualización disponible, abajo en la barra lateral.",
    "You have {current}.": "Tienes la {current}.",
    "Update Piklin": "Actualizar Piklin",
    "You have version {current}. This update takes you to version {version}. Your library, albums, edits and backups stay as they are.":
        "Estás en la versión {current}. Esta actualización te lleva a la versión {version}. Tu biblioteca, álbumes, cambios y copias de seguridad se quedan como están.",
    "This version brings improvements and fixes.": "Esta versión trae mejoras y arreglos.",
    "Later": "Más tarde",
    "Installing…": "Instalando…",
    "Install and Reopen": "Instalar y reabrir",
    "What's New": "Novedades",
    "Piklin notes what it does here - backups, imports, updates and errors - only to help find the cause of a problem. The log stays on this computer and is never sent anywhere. It holds no passwords, addresses or names of your photos, and it never grows past {size}.":
        "Piklin anota aquí lo que hace - copias de seguridad, importaciones, actualizaciones y errores - solo para ayudar a encontrar la causa de un problema. El registro se queda en esta computadora y nunca se envía a ningún lugar. No guarda contraseñas, direcciones ni nombres de tus fotos, y nunca pasa de {size}.",
    "Something went wrong? Press Copy, then Report a Problem, describe what happened and paste the log into the report.":
        "¿Algo salió mal? Pulsa Copiar, luego Informar de un problema, cuenta qué pasó y pega el registro en el informe.",
    "Copy": "Copiar",
    "Report a Problem…": "Informar de un problema…",
    "Opens a new problem report on GitHub in your browser": "Abre un nuevo informe de problema en GitHub, en tu navegador",
    "Open Folder": "Abrir carpeta",
    "Clear": "Borrar",
    "Nothing has been noted yet.": "Todavía no se ha anotado nada.",
    "Log copied": "Registro copiado",
    "Piklin will try again in a few minutes": "Piklin lo volverá a intentar en unos minutos",
    "Edit this backup and enter the password again": "Edita esta copia y vuelve a escribir la contraseña",
    "Couldn't create the folder /{folder}": "No se pudo crear la carpeta /{folder}",
    "The server answered HTTP {code}. The folder must be inside a shared folder you can write to":
        "El servidor respondió HTTP {code}. La carpeta tiene que estar dentro de una carpeta compartida donde puedas escribir",
    "created the folder /{folder}": "se creó la carpeta /{folder}",
    "Wrong username or password": "Usuario o contraseña incorrectos",
    "Check the username and password": "Revisa el usuario y la contraseña",
    "Not allowed": "Sin permiso",
    "This account isn't allowed to use that folder": "Esta cuenta no tiene permiso para usar esa carpeta",
    "This address doesn't accept backups": "Esta dirección no acepta copias",
    "Turn on WebDAV on your server and use the address it shows for it. On a QNAP: Control Panel › Network & File Services › Win/Mac/NFS/WebDAV":
        "Activa WebDAV en tu servidor y usa la dirección que muestra. En un QNAP: Panel de control › Servicios de red y archivos › Win/Mac/NFS/WebDAV",
    "The server says to use another address": "El servidor indica que uses otra dirección",
    "Try {address}": "Prueba {address}",
    "This folder isn't on the server": "Esta carpeta no está en el servidor",
    "Check the address and the folder": "Revisa la dirección y la carpeta",
    "The server answered HTTP {code}": "El servidor respondió HTTP {code}",
    "The server's security certificate has changed": "El certificado de seguridad del servidor cambió",
    "Trust the new one only if you replaced it yourself": "Confía en el nuevo solo si lo cambiaste tú",
    "Confirm this server is yours": "Confirma que este servidor es tuyo",
    "It uses its own security certificate, which is normal for a NAS at home":
        "Usa su propio certificado de seguridad, algo normal en un NAS de casa",
    "A secure connection couldn't be made": "No se pudo hacer una conexión segura",
    "Can't reach the server": "No se puede conectar con el servidor",
    "rclone is not installed": "rclone no está instalado",
    "Install rclone to use Google Drive, OneDrive, Dropbox, pCloud and more: sudo apt install rclone (then run: rclone config)":
        "Instala rclone para usar Google Drive, OneDrive, Dropbox, pCloud y más: sudo apt install rclone (y luego ejecuta: rclone config)",
    "Enter the name of the cloud service": "Escribe el nombre del servicio en la nube",
    "Set up in rclone: {names}": "Configurados en rclone: {names}",
    "none": "ninguno",
    "rclone can't reach the cloud service": "rclone no puede conectar con el servicio en la nube",
    "The cloud service took too long to answer": "El servicio en la nube tardó demasiado en responder",
    "rclone failed": "rclone falló",
    "Enter the name of the cloud service first": "Primero escribe el nombre del servicio en la nube",
    "rclone stopped with error {code}": "rclone se detuvo con el error {code}",
    "rclone not installed": "rclone no está instalado",
    "Folder or Drive": "Carpeta o unidad",
    "A USB drive, a network folder from your NAS, or a folder that Dropbox or pCloud Drive keeps in sync. No password needed.":
        "Una unidad USB, una carpeta de red de tu NAS o una carpeta que Dropbox o pCloud Drive sincronizan. No necesita contraseña.",
    "NAS or Server (WebDAV)": "NAS o servidor (WebDAV)",
    "For QNAP, Synology, Nextcloud and similar. You need the server address, your username and your password.":
        "Para QNAP, Synology, Nextcloud y similares. Necesitas la dirección del servidor, tu usuario y tu contraseña.",
    "Cloud Service (rclone)": "Servicio en la nube (rclone)",
    "({count} set up)": "({count} configurados)",
    "Google Drive, OneDrive, Dropbox, Backblaze and about seventy more, through the free rclone app. For advanced users.":
        "Google Drive, OneDrive, Dropbox, Backblaze y unos setenta más, con la aplicación gratuita rclone. Para usuarios avanzados.",
    "Not installed yet. Install the free rclone app to use Google Drive, OneDrive, Dropbox and many more.":
        "Todavía no está instalado. Instala la aplicación gratuita rclone para usar Google Drive, OneDrive, Dropbox y muchos más.",

    # -- editor ------------------------------------------------------------------------
    "Back to library": "Volver a la biblioteca",
    "Undo (Ctrl+Z)": "Deshacer (Ctrl+Z)",
    "Redo (Ctrl+Shift+Z)": "Rehacer (Ctrl+Mayús+Z)",
    "Hold to compare with original (M)": "Mantén pulsado para comparar con el original (M)",
    "Remove all edits": "Quitar todos los cambios",
    "Export…": "Exportar…",
    "Tools": "Herramientas",
    "Edits": "Cambios",
    "A Look adds edits you can still change or remove.": "Un estilo añade cambios que puedes modificar o quitar después.",
    "No edits yet.\nPick a tool to begin.": "Todavía no hay cambios.\nElige una herramienta para empezar.",
    "Remove this edit": "Quitar este cambio",
    "Double-click to add a point, right-click to remove.": "Doble clic para añadir un punto, clic derecho para quitarlo.",
    "Reset curve": "Restablecer curva",
    "Choose image…": "Elegir imagen…",
    "Drag on the photo to set the crop.": "Arrastra sobre la foto para recortar.",
    "Click the photo to drop a control point.": "Haz clic en la foto para poner un punto.",
    "Drag on the photo to paint.": "Arrastra sobre la foto para pintar.",
    "Drag over what you want removed.": "Arrastra sobre lo que quieras quitar.",
    "Click the photo to position this.": "Haz clic en la foto para colocarlo.",
    "Clear": "Borrar",
    "Strength": "Intensidad",
    "Choose a photo to blend": "Elige una foto para mezclar",
    "{percent}% strength": "{percent}% de intensidad",
    "Remove all edits?": "¿Quitar todos los cambios?",
    "Your original photo is untouched either way — this just clears the adjustments you have made to it.":
        "Tu foto original no se toca en ningún caso: esto solo borra los ajustes que le hiciste.",
    "Cancel": "Cancelar",
    "Remove Edits": "Quitar cambios",

    # -- export ------------------------------------------------------------------------
    "Export": "Exportar",
    "{count} photo": ("{count} foto", "{count} fotos"),
    "{count} video": ("{count} video", "{count} videos"),
    "{photos} and {videos}": "{photos} y {videos}",
    "Nothing": "Nada",
    "Save to": "Guardar en",
    "Change…": "Cambiar…",
    "File Size": "Tamaño del archivo",
    "Piklin tries each option on your photos to show how much smaller they get.":
        "Piklin prueba cada opción con tus fotos para mostrar cuánto se reducen.",
    "Format": "Formato",
    "Same as original": "Igual que el original",
    "Full Size": "Tamaño completo",
    "Large (2048 px)": "Grande (2048 px)",
    "Medium (1280 px)": "Mediano (1280 px)",
    "Small (640 px)": "Pequeño (640 px)",
    "Video": "Video",
    "Edited videos are saved with your trims, cuts and changes. The original files are never changed.":
        "Los videos editados se guardan con tus recortes, cortes y cambios. Los archivos originales nunca se modifican.",
    "Same as Original": "Igual que el original",
    "Video Quality": "Calidad del video",
    "Include": "Incluir",
    "Location": "Ubicación",
    "Where it was taken (GPS)": "Dónde se tomó (GPS)",
    "Remove all hidden details": "Quitar todos los datos ocultos",
    "Also removes the camera and the date it was taken": "También quita la cámara y la fecha de la foto",
    "File Names": "Nombres de archivo",
    "File Name": "Nombre de archivo",
    "Use File Name": "Usar el nombre del archivo",
    "Use Title": "Usar el título",
    "Numbered": "Numerados",
    "Put in Folders by": "Poner en carpetas por",
    "No Folders": "Sin carpetas",
    "Date": "Fecha",
    "Measuring…": "Midiendo…",
    "Trying each option on a few of your photos": "Probando cada opción con algunas de tus fotos",
    "Export Original Without Edits": "Exportar original sin cambios",
    "{percent}% match": "{percent}% igual",
    "no saving": "sin ahorro",
    "Ready": "Listo",
    "Sizes measured on a few of the selected photos": "Tamaños medidos con algunas de las fotos elegidas",
    "Library exports, filed by date": "Exportaciones de la biblioteca, por fecha",
    "Your pictures folder": "Tu carpeta Imágenes",
    "Desktop": "Escritorio",
    "Downloads": "Descargas",
    "Home folder": "Carpeta personal",
    "Export to": "Exportar a",
    "Choose where the exported photos should go.": "Elige dónde guardar las fotos exportadas.",
    "…or type another folder path": "…o escribe la ruta de otra carpeta",
    "Use Folder": "Usar carpeta",
    "Exporting…": "Exportando…",
    "Exporting originals…": "Exportando originales…",
    "Exported {count} item": ("Se exportó {count} elemento", "Se exportaron {count} elementos"),
    "to {folder}": "a {folder}",
    "{count} failed": ("{count} falló", "{count} fallaron"),

    # -- folders -----------------------------------------------------------------------
    "This Folder Is Empty": "Esta carpeta está vacía",
    "Drag albums onto this folder in the sidebar to group them.":
        "Arrastra álbumes a esta carpeta en la barra lateral para agruparlos.",
    "{count} album": ("{count} álbum", "{count} álbumes"),
    "{count} folder": ("{count} carpeta", "{count} carpetas"),

    # -- photo grid ------------------------------------------------------------------------
    "No Date": "Sin fecha",
    "Today": "Hoy",
    "Yesterday": "Ayer",
    "No photos here yet": "Todavía no hay fotos aquí",
    "Add a folder and Piklin will build your library.": "Añade una carpeta y Piklin creará tu biblioteca.",
    "Photo": "Foto",
    "Already Imported": "Ya importadas",
    "{count} item already in your library": ("{count} elemento ya está en tu biblioteca", "{count} elementos ya están en tu biblioteca"),
    "New Items": "Elementos nuevos",
    "No Photos": "No hay fotos",
    "Add a folder of photos, or connect a camera, and they will appear here.":
        "Añade una carpeta de fotos o conecta una cámara, y aparecerán aquí.",
    "No Favourites": "No hay favoritos",
    "Select photos and press the period key (.) to add them to your favourites.":
        "Selecciona fotos y pulsa la tecla del punto (.) para añadirlas a tus favoritos.",
    "No Edited Photos": "No hay fotos editadas",
    "Photos you edit appear here. Your originals are never changed.":
        "Las fotos que edites aparecen aquí. Tus originales nunca se modifican.",
    "No Hidden Photos": "No hay fotos ocultas",
    "Select photos and press Ctrl+L to hide them from the library.":
        "Selecciona fotos y pulsa Ctrl+L para ocultarlas de la biblioteca.",
    "No Recently Deleted Items": "No hay elementos eliminados recientemente",
    "Deleted photos stay here for 30 days before they leave the library.":
        "Las fotos eliminadas se quedan aquí 30 días antes de salir de la biblioteca.",
    "This Album Is Empty": "Este álbum está vacío",
    "Drag photos onto the album in the sidebar to add them.": "Arrastra fotos al álbum en la barra lateral para añadirlas.",
    "No Screenshots": "No hay capturas de pantalla",
    "Screenshots in your folders appear here.": "Las capturas de pantalla de tus carpetas aparecen aquí.",
    "No Videos": "No hay videos",
    "Videos in your folders and from your camera appear here.": "Los videos de tus carpetas y de tu cámara aparecen aquí.",
    "No Duplicates": "No hay duplicados",
    "Photos that are exact copies of each other are gathered here.": "Aquí se reúnen las fotos que son copias exactas.",
    "No Imports": "No hay importaciones",
    "Photos you import from a camera appear here, newest import first.":
        "Las fotos que importes de una cámara aparecen aquí, primero la importación más reciente.",
    "No Matching Photos": "No hay fotos que coincidan",
    "Nothing here matches the filter. Choose Show All in the Filter menu.":
        "Nada coincide con el filtro. Elige Mostrar todo en el menú Filtro.",
    "No Results": "Sin resultados",
    "Nothing matches “{search}”.": "Nada coincide con “{search}”.",

    # -- photo picker, player, rename -----------------------------------------------------
    "Choose a photo": "Elige una foto",
    "Search your photos": "Busca en tus fotos",
    "No photos found": "No se encontraron fotos",
    "There is no picture in this file.": "Este archivo no tiene imagen.",
    "This video could not be opened.": "No se pudo abrir este video.",
    "Play (Space)": "Reproducir (Espacio)",
    "Playback Speed": "Velocidad de reproducción",
    "Loop": "Repetir",
    "Mute (M)": "Silenciar (M)",
    "Full Screen (F11)": "Pantalla completa (F11)",
    "This video can't be played.": "Este video no se puede reproducir.",
    "Pause (Space)": "Pausa (Espacio)",
    "Rename Photo": "Cambiar nombre de la foto",
    "The file is renamed on your computer too, so you'll see the new name everywhere.":
        "El archivo también cambia de nombre en tu ordenador, así verás el nombre nuevo en todas partes.",
    "New name": "Nombre nuevo",
    "Rename": "Cambiar nombre",
    "There is already a file named “{name}”.": "Ya hay un archivo llamado “{name}”.",
    "Couldn’t Rename": "No se pudo cambiar el nombre",
    "Couldn't read this photo from {device}.": "No se pudo leer esta foto de {device}.",
    "OK": "Aceptar",

    # -- preferences -------------------------------------------------------------------------
    "Preferences": "Preferencias",
    "General": "General",
    "Appearance": "Apariencia",
    "Theme": "Tema",
    "Light": "Claro",
    "Group photos by": "Agrupar fotos por",
    "Don't group": "No agrupar",
    "Day": "Día",
    "Month": "Mes",
    "Year": "Año",
    "Show file names under photos": "Mostrar los nombres de archivo debajo de las fotos",
    "Speed": "Velocidad",
    "How sharp photos look while you edit. Higher looks better, but each change can take a little longer.":
        "Qué tan nítidas se ven las fotos mientras editas. Más alto se ve mejor, pero cada cambio puede tardar un poco más.",
    "Preview quality while editing": "Calidad de la vista previa al editar",
    "Higher looks sharper, lower feels faster": "Más alto se ve más nítido; más bajo va más rápido",
    "Preview quality while moving a slider": "Calidad de la vista previa al mover un control",
    "Lower feels smoother": "Más bajo se siente más fluido",
    "Privacy": "Privacidad",
    "Piklin has no accounts and collects nothing about you. Your photos only leave this computer if you set up a backup.":
        "Piklin no tiene cuentas y no recoge nada sobre ti. Tus fotos solo salen de este ordenador si configuras una copia de seguridad.",
    "Find faces for the portrait tools": "Buscar caras para las herramientas de retrato",
    "Done on this computer. Nothing is ever uploaded.": "Se hace en este ordenador. Nunca se sube nada.",
    "Check for updates": "Buscar actualizaciones",
    "Once a day, Piklin asks GitHub whether a new version is out. Nothing about you or your photos is sent.":
        "Una vez al día, Piklin pregunta a GitHub si hay una versión nueva. No se envía nada sobre ti ni sobre tus fotos.",
    "Storage": "Almacenamiento",
    "Photo Size When Exporting": "Tamaño de las fotos al exportar",
    "Piklin tries each option on your photos and shows how much smaller the files get.":
        "Piklin prueba cada opción con tus fotos y muestra cuánto se reducen los archivos.",
    "Export Format": "Formato de exportación",
    "JPEG opens everywhere. WebP and AVIF make smaller files.": "JPEG se abre en todas partes. WebP y AVIF ocupan menos.",
    "Remove hidden details from exported photos": "Quitar los datos ocultos de las fotos exportadas",
    "The camera, date and place are removed from the copy": "Se quitan la cámara, la fecha y el lugar de la copia",
    "Importing": "Importar",
    "How photos are brought into the library.": "Cómo entran las fotos en la biblioteca.",
    "When adding a folder": "Al añadir una carpeta",
    "Leave photos where they are": "Dejar las fotos donde están",
    "Copy them into the library": "Copiarlas a la biblioteca",
    "Move them into the library": "Moverlas a la biblioteca",
    "With the first option, your folders are never changed": "Con la primera opción, tus carpetas nunca se modifican",
    "(recommended)": "(recomendado)",
    "Make imported photos smaller": "Reducir las fotos importadas",
    "Only photos from a camera or memory card. Your folders are never changed.":
        "Solo las fotos de una cámara o tarjeta de memoria. Tus carpetas nunca se modifican.",
    "Videos when importing": "Videos al importar",
    "Smaller files save space. Keep the originals if you want the best quality for editing later.":
        "Los archivos pequeños ahorran espacio. Guarda los originales si quieres la mejor calidad para editar después.",
    "Keep Original Files": "Guardar los archivos originales",
    "Smaller Files": "Archivos más pequeños",
    "Space Used": "Espacio usado",
    "Library": "Biblioteca",
    "Photo previews": "Vistas previas",
    "{size} of originals": "{size} de originales",
    "rebuilt automatically when needed": "se regeneran solas cuando hace falta",
    "Cleared {size}": "Se liberaron {size}",
    "Backup": "Copia de seguridad",
    "Keep a Copy of Your Photos": "Guarda una copia de tus fotos",
    "Piklin can copy your library to a drive, a NAS or a cloud service, so your photos are safe even if something happens to this computer.":
        "Piklin puede copiar tu biblioteca a una unidad, un NAS o un servicio en la nube, para que tus fotos estén a salvo aunque le pase algo a este ordenador.",
    "Your Backups": "Tus copias",
    "Automatic Backup": "Copia automática",
    "Back Up Automatically": "Copiar automáticamente",
    "New photos, videos and edits are copied a minute after they change. Nothing happens when nothing changed, and it waits while battery saver is on.":
        "Las fotos, videos y cambios nuevos se copian un minuto después de cambiar. Si no cambia nada, no hace nada, y espera mientras el ahorro de batería está activo.",
    "Keep Older Versions": "Guardar versiones anteriores",
    "When a photo or edit changes, the previous copy stays in the backup for this long.":
        "Cuando una foto o un cambio se modifica, la copia anterior se queda en la copia de seguridad este tiempo.",
    "7 days": "7 días",
    "30 days": "30 días",
    "90 days": "90 días",
    "Add a Place to Back Up": "Añadir un lugar para la copia",
    "Passwords": "Contraseñas",
    "Saved safely in your computer's password manager.": "Se guardan con seguridad en el gestor de contraseñas de tu ordenador.",
    "This computer has no password manager, so only folders and drives can be used.":
        "Este ordenador no tiene gestor de contraseñas, así que solo se pueden usar carpetas y unidades.",
    "No backups set up yet": "Todavía no hay copias configuradas",
    "Choose a place below to keep a copy of your photos.": "Elige abajo un lugar para guardar una copia de tus fotos.",
    "Back Up Now": "Copiar ahora",
    "More Options": "Más opciones",
    "Check Connection": "Comprobar conexión",
    "Restore Missing Files…": "Recuperar archivos que faltan…",
    "Edit…": "Editar…",
    "Remove": "Quitar",
    "{size} free": "{size} libres",
    "Choose a backup folder": "Elige una carpeta para la copia",
    "Edit Backup": "Editar copia",
    "Enter your server's address (it starts with https://, or http:// at home), your username and password. Then choose a folder with the folder button.":
        "Escribe la dirección de tu servidor (empieza con https://, o http:// en casa), tu usuario y tu contraseña. Luego elige una carpeta con el botón de carpeta.",
    "Enter the name of a cloud service you set up in rclone, with the command rclone config.":
        "Escribe el nombre de un servicio en la nube que configuraste en rclone con el comando rclone config.",
    "Name": "Nombre",
    "Server address": "Dirección del servidor",
    "Folder on the server": "Carpeta en el servidor",
    "Username": "Usuario",
    "Password (leave empty to keep it)": "Contraseña (déjala vacía para mantenerla)",
    "Password": "Contraseña",
    "Name in rclone": "Nombre en rclone",
    "Folder in the cloud": "Carpeta en la nube",
    "Save": "Guardar",
    "Add": "Añadir",
    "The password couldn't be saved because your password manager is locked. Unlock it and edit this backup again.":
        "No se pudo guardar la contraseña porque tu gestor de contraseñas está bloqueado. Desbloquéalo y vuelve a editar esta copia.",
    "Choose a Folder": "Elegir carpeta",
    "Use This Folder": "Usar esta carpeta",
    "Top Level": "Nivel principal",
    "Connecting…": "Conectando…",
    "Back": "Atrás",
    "There are no folders here. You can use this one, or type a new folder name at the end and Piklin will create it.":
        "Aquí no hay carpetas. Puedes usar esta o escribir al final el nombre de una carpeta nueva y Piklin la creará.",
    "Security Certificate Changed": "Cambió el certificado de seguridad",
    "Trust This Server?": "¿Confiar en este servidor?",
    "The security certificate of <b>{server}</b> is not the one you trusted before. If you didn't replace it yourself, don't continue.":
        "El certificado de seguridad de <b>{server}</b> no es el que aceptaste antes. Si no lo cambiaste tú, no continúes.",
    "<b>{server}</b> uses its own security certificate, which is normal for a server at home. Check that this fingerprint matches the one your server shows, then trust it.":
        "<b>{server}</b> usa su propio certificado de seguridad, algo normal en un servidor de casa. Comprueba que esta huella coincide con la que muestra tu servidor y luego confía en él.",
    "Trust This Server": "Confiar en este servidor",
    "Testing…": "Probando…",
    "Checking what is already backed up": "Comprobando lo que ya está copiado",
    "Backing up": "Copiando",
    "Backed up {count} file": ("Se copió {count} archivo", "Se copiaron {count} archivos"),
    "{count} already backed up": ("{count} ya estaba copiado", "{count} ya estaban copiados"),
    "Stopped": "Detenido",
    "Restore Missing Files?": "¿Recuperar los archivos que faltan?",
    "Piklin copies back from “{backup}” the photos, videos, edits and albums that are missing from your library.\n\nNothing in your library is replaced, and photos you deleted yourself stay deleted.":
        "Piklin copia de vuelta desde “{backup}” las fotos, videos, cambios y álbumes que faltan en tu biblioteca.\n\nNo se reemplaza nada de tu biblioteca, y las fotos que borraste tú siguen borradas.",
    "the backup": "la copia",
    "Restore": "Recuperar",
    "Reading the backup…": "Leyendo la copia…",
    "Restoring — {done} of {total} ({size})": "Recuperando — {done} de {total} ({size})",
    "Restored {count} file": ("Se recuperó {count} archivo", "Se recuperaron {count} archivos"),
    "{count} already in your library": ("{count} ya estaba en tu biblioteca", "{count} ya estaban en tu biblioteca"),
    "{count} you deleted left out": ("{count} que borraste se dejó fuera", "{count} que borraste se dejaron fuera"),
    "Reopen Piklin to Finish": "Reabre Piklin para terminar",
    "{count} file is back. Piklin reopens and rebuilds your library, with your albums, favourites and edits.":
        ("{count} archivo está de vuelta. Piklin se reabre y reconstruye tu biblioteca, con tus álbumes, favoritos y cambios.",
         "{count} archivos están de vuelta. Piklin se reabre y reconstruye tu biblioteca, con tus álbumes, favoritos y cambios."),
    "Later": "Más tarde",
    "Reopen Now": "Reabrir ahora",
    "Where Your Library Is": "Dónde está tu biblioteca",
    "Everything Piklin keeps is in this one package, so copying it copies everything. You can move it anywhere, even to another drive, and open it with Open Library… in the menu.":
        "Todo lo que guarda Piklin está en este paquete, así que al copiarlo copias todo. Puedes moverlo a cualquier sitio, incluso a otra unidad, y abrirlo con Abrir biblioteca… en el menú.",
    "Your Photo Folders": "Tus carpetas de fotos",
    "Photos in these folders stay where they are. Piklin never moves or changes them.":
        "Las fotos de estas carpetas se quedan donde están. Piklin nunca las mueve ni las modifica.",
    "None yet": "Ninguna todavía",
    "Stop using this folder (the files stay)": "Dejar de usar esta carpeta (los archivos se quedan)",
    "Maintenance": "Mantenimiento",
    "Piklin keeps a list of your photos to find them quickly. If something looks wrong, the list can be rebuilt without losing anything.":
        "Piklin guarda una lista de tus fotos para encontrarlas rápido. Si algo se ve mal, la lista se puede reconstruir sin perder nada.",
    "Find Duplicate Photos": "Buscar fotos duplicadas",
    "Finds photos that are exact copies": "Encuentra las fotos que son copias exactas",
    "Find": "Buscar",
    "Photos Removed from Piklin": "Fotos quitadas de Piklin",
    "{count} photo you removed doesn't come back, even though its file is still in your folders":
        ("{count} foto que quitaste no vuelve, aunque su archivo sigue en tus carpetas",
         "{count} fotos que quitaste no vuelven, aunque sus archivos siguen en tus carpetas"),
    "Photos you remove don't come back, even though their files are still in your folders":
        "Las fotos que quitas no vuelven, aunque sus archivos sigan en tus carpetas",
    "Show Again": "Volver a mostrar",
    "Rebuild the Photo List": "Reconstruir la lista de fotos",
    "Close Piklin and run: piklin --rebuild-index": "Cierra Piklin y ejecuta: piklin --rebuild-index",
    "They'll be back in a moment": "Volverán en un momento",
    "{count} photo will be back in a moment.": ("{count} foto volverá en un momento.", "{count} fotos volverán en un momento."),
    "Folder removed from the library. No files were deleted.": "Carpeta quitada de la biblioteca. No se borró ningún archivo.",
    "Scanning…": "Buscando…",
    "{count} group": ("{count} grupo", "{count} grupos"),
    "{count} duplicate file": ("{count} archivo duplicado", "{count} archivos duplicados"),
    "using {size}": "que ocupan {size}",
    "No duplicates found": "No se encontraron duplicados",
    "Language": "Idioma",
    "Reopen Piklin?": "¿Reabrir Piklin?",
    "Piklin needs to reopen to show everything in the new language.":
        "Piklin necesita reabrirse para mostrar todo en el idioma nuevo.",

    # -- smart albums ------------------------------------------------------------------------
    "value": "valor",
    "Remove this condition": "Quitar esta condición",
    "Add a condition": "Añadir una condición",
    "days, or YYYY-MM-DD": "días, o AAAA-MM-DD",
    "number": "número",
    "text": "texto",
    "Smart Album": "Álbum inteligente",
    "Smart Album Name:": "Nombre del álbum inteligente:",
    "Match": "Coincidir con",
    "of the following conditions:": "de estas condiciones:",
    "{count} photo matches": ("{count} foto coincide", "{count} fotos coinciden"),
    "Check the values of the conditions": "Revisa los valores de las condiciones",

    # -- video editor -------------------------------------------------------------------------
    "Revert to Original": "Volver al original",
    "Trim": "Recortar",
    "Drag the white handles on the timeline, or set them here.": "Arrastra los tiradores blancos de la línea de tiempo o ajústalos aquí.",
    "Start": "Inicio",
    "Set Here": "Poner aquí",
    "Start here (I)": "Empezar aquí (I)",
    "End": "Final",
    "End here (O)": "Terminar aquí (O)",
    "Cut Out": "Cortar",
    "Hold Shift and drag on the timeline, or mark the start and end, then cut it out.":
        "Mantén Mayús y arrastra en la línea de tiempo, o marca el inicio y el final, y luego córtalo.",
    "Selection": "Selección",
    "Mark Start": "Marcar inicio",
    "Mark the start ([)": "Marcar el inicio ([)",
    "Mark End": "Marcar final",
    "Mark the end (])": "Marcar el final (])",
    "Cut Out Selection": "Cortar la selección",
    "Cut out (X)": "Cortar (X)",
    "Playback": "Reproducción",
    "Voices sound normal at any speed": "Las voces suenan normales a cualquier velocidad",
    "Mute": "Silenciar",
    "Export without sound": "Exportar sin sonido",
    "Picture": "Imagen",
    "Rotate and Flip": "Girar y voltear",
    "Rotate Left": "Girar a la izquierda",
    "Rotate Right": "Girar a la derecha",
    "Cover Frame": "Fotograma de portada",
    "The frame shown in the library": "El fotograma que se ve en la biblioteca",
    "Use This Frame": "Usar este fotograma",
    "Save Frame as Photo": "Guardar fotograma como foto",
    "Full resolution, into your library": "A resolución completa, en tu biblioteca",
    "Save the frame you are seeing": "Guardar el fotograma que estás viendo",
    "Beginning": "Principio",
    "{length} after editing": "{length} después de editar",
    "Nothing selected": "Nada seleccionado",
    "Pieces Cut Out": "Partes cortadas",
    "Poster frame set": "Fotograma de portada elegido",
    "The frame couldn’t be saved: {error}": "No se pudo guardar el fotograma: {error}",
    "Revert to Original?": "¿Volver al original?",
    "Your video file is untouched either way — this clears the trims, cuts and other changes made to it.":
        "Tu archivo de video no se toca en ningún caso: esto borra los recortes, cortes y otros cambios que le hiciste.",
    "Revert": "Volver al original",

    # -- viewer ------------------------------------------------------------------------------
    "Play the live photo": "Reproducir la foto en movimiento",
    "Back (Esc)": "Atrás (Esc)",
    "Previous": "Anterior",
    "Next": "Siguiente",
    "Favourite (F)": "Favorito (F)",
    "Info (Ctrl+I)": "Información (Ctrl+I)",
    "Edit": "Editar",
    "Move to Recently Deleted (Delete)": "Mover a Eliminados recientemente (Supr)",
    "Add a Title": "Añade un título",
    "Add a Caption": "Añade una descripción",
    "Add Keywords": "Añade palabras clave",
    "File": "Archivo",
    "Dimensions": "Dimensiones",
    "Length": "Duración",
    "Taken": "Tomada",
    "Albums": "Álbumes",
    "Folder": "Carpeta",
    "Adjust Date and Time": "Ajustar fecha y hora",
    "Adjust Location": "Ajustar ubicación",
    "Rename (F2)": "Cambiar nombre (F2)",
    "Rotate Left (Ctrl+Shift+R)": "Girar a la izquierda (Ctrl+Mayús+R)",
    "Rotate Right (Ctrl+R)": "Girar a la derecha (Ctrl+R)",
    "set by you": "puesta por ti",
    "from the file": "según el archivo",
    "from the file name": "según el nombre del archivo",
    "{date}, {time}": "{date}, {time}",
    "{count} change": ("{count} cambio", "{count} cambios"),
    "None, it's the original": "Ninguno, es el original",
    "The photo file isn't changed. The new date is saved in Piklin.": "El archivo de la foto no cambia. La fecha nueva se guarda en Piklin.",
    "YYYY-MM-DD HH:MM": "AAAA-MM-DD HH:MM",
    "Enter the latitude and longitude, for example 40.41680, -3.70380. You can copy them from a map app.":
        "Escribe la latitud y la longitud, por ejemplo 40.41680, -3.70380. Puedes copiarlas de una aplicación de mapas.",
    "latitude, longitude": "latitud, longitud",
    "Remove Location": "Quitar ubicación",

    # -- main window ---------------------------------------------------------------------------
    "Photos": "Fotos",
    "Newest First": "Más recientes primero",
    "Oldest First": "Más antiguas primero",
    "Recently Added": "Añadidas recientemente",
    "Sort By": "Ordenar por",
    "Open Library…": "Abrir biblioteca…",
    "Add Folder…": "Añadir carpeta…",
    "Look for New Photos": "Buscar fotos nuevas",
    "Backups…": "Copias de seguridad…",
    "Storage…": "Almacenamiento…",
    "Check for Updates…": "Buscar actualizaciones…",
    "About Piklin": "Acerca de Piklin",
    "Main Menu": "Menú principal",
    "Support Piklin": "Apoyar a Piklin",
    "Support on Ko-fi": "Apoyar en Ko-fi",
    "Search photos": "Buscar fotos",
    "Years": "Años",
    "Months": "Meses",
    "Days": "Días",
    "All Photos": "Todas las fotos",
    "Photo size": "Tamaño de las fotos",
    "Filter": "Filtro",
    "Filter photos": "Filtrar fotos",
    "Favourites": "Favoritos",
    "Videos": "Videos",
    "Screenshots": "Capturas de pantalla",
    "Not in an Album": "Sin álbum",
    "Has Location": "Con ubicación",
    "Show All": "Mostrar todo",
    "Show whole photos instead of squares": "Mostrar las fotos completas en vez de cuadradas",
    "Move to Recently Deleted": "Mover a Eliminados recientemente",
    "Add to Album…": "Añadir a un álbum…",
    "Import": "Importar",
    "Delete from the camera after importing": "Borrar de la cámara después de importar",
    "Import to": "Importar a",
    "Import to:": "Importar a:",
    "Keep One": "Dejar una",
    "Delete Permanently…": "Eliminar definitivamente…",
    "Unselect": "Quitar selección",
    "{count} Photo": ("{count} foto", "{count} fotos"),
    "{count} Video": ("{count} video", "{count} videos"),
    "{used} of {total}": "{used} de {total}",
    "New Album or Folder": "Nuevo álbum o carpeta",
    "Devices": "Dispositivos",
    "Recently Deleted": "Eliminados recientemente",
    "Types": "Tipos",
    "Utilities": "Utilidades",
    "Hidden": "Ocultas",
    "Duplicates": "Duplicados",
    "Recently Edited": "Editadas recientemente",
    "Imports": "Importaciones",
    "New Album…": "Nuevo álbum…",
    "New Smart Album…": "Nuevo álbum inteligente…",
    "New Folder…": "Nueva carpeta…",
    "Reading {device}…": "Leyendo {device}…",
    "Reading {device}… {count} found": "Leyendo {device}… {count} encontradas",
    "Stop": "Detener",
    "Stop copying (what is already copied stays)": "Detener la copia (lo ya copiado se queda)",
    "Stopping…": "Deteniendo…",
    "Photos are already being copied. Wait until they finish, or stop that copy first.":
        "Ya se están copiando fotos. Espera a que terminen o detén esa copia primero.",
    "{step} — {done} of {total}": "{step} — {done} de {total}",
    "Copying {count} item. You can keep using Piklin while it copies.":
        ("Copiando {count} elemento. Puedes seguir usando Piklin mientras se copia.",
         "Copiando {count} elementos. Puedes seguir usando Piklin mientras se copian."),
    "Imported {count} item into “{album}”": ("Se importó {count} elemento a “{album}”", "Se importaron {count} elementos a “{album}”"),
    "Imported {count} item": ("Se importó {count} elemento", "Se importaron {count} elementos"),
    "{count} could not be copied": ("{count} no se pudo copiar", "{count} no se pudieron copiar"),
    "Stopped. {summary}": "Detenido. {summary}",
    "Importing from {device}": "Importando de {device}",
    "Importing into “{album}”": "Importando a “{album}”",
    "Getting the photos ready…": "Preparando las fotos…",
    "Stopped. Nothing was copied.": "Detenido. No se copió nada.",
    "There are no photos or videos in what you dropped.": "No hay fotos ni videos en lo que soltaste.",
    "Copying into “{album}”": "Copiando a “{album}”",
    "Copying": "Copiando",
    "Delete {count} item from “{device}”?": ("¿Borrar {count} elemento de “{device}”?", "¿Borrar {count} elementos de “{device}”?"),
    "They are safely in your library now. Deleting them frees up space on the camera and can't be undone.":
        "Ya están a salvo en tu biblioteca. Borrarlos libera espacio en la cámara y no se puede deshacer.",
    "Keep Items": "Conservar",
    "Delete Items": "Borrar",
    "Deleted {count} item from {device}": ("Se borró {count} elemento de {device}", "Se borraron {count} elementos de {device}"),
    "({count} could not be deleted)": ("({count} no se pudo borrar)", "({count} no se pudieron borrar)"),
    "Frame saved to your library": "Fotograma guardado en tu biblioteca",
    "Piklin {version} is available": "Piklin {version} está disponible",
    "Download": "Descargar",
    "Couldn't check for updates. Check your internet connection and try again.":
        "No se pudo buscar actualizaciones. Revisa tu conexión a internet e inténtalo de nuevo.",
    "Piklin is up to date ({version}).": "Piklin está al día ({version}).",
    "Select the photos to rotate.": "Selecciona las fotos que quieres girar.",
    "{count} selected": "{count} seleccionadas",
    "Import {count} Selected": "Importar {count} seleccionadas",
    "Import All New Items ({count})": "Importar todo lo nuevo ({count})",
    "All Items Imported": "Todo importado",
    "Delete All…": "Eliminar todo…",
    "Keep One of {count}": "Dejar una de {count}",
    "Recover All": "Recuperar todo",
    "Recover": "Recuperar",
    "Remove from this album": "Quitar de este álbum",
    "Kept one. {count} extra copy moved to Recently Deleted.":
        ("Se dejó una. {count} copia de más se movió a Eliminados recientemente.",
         "Se dejó una. {count} copias de más se movieron a Eliminados recientemente."),
    "Select at least two copies of the same photo.": "Selecciona al menos dos copias de la misma foto.",
    "Delete {count} photo permanently?": ("¿Eliminar {count} foto definitivamente?", "¿Eliminar {count} fotos definitivamente?"),
    "These photos are in a folder on your computer.\n\n“Remove from Library” only takes them out of Piklin. The files stay where they are.\n\n“Delete Files” deletes the files from your computer. This can't be undone.":
        "Estas fotos están en una carpeta de tu ordenador.\n\n“Quitar de la biblioteca” solo las saca de Piklin. Los archivos se quedan donde están.\n\n“Borrar archivos” borra los archivos de tu ordenador. No se puede deshacer.",
    "Remove from Library": "Quitar de la biblioteca",
    "Delete Files": "Borrar archivos",
    "Filter ({count})": "Filtro ({count})",
    "Add to Album": "Añadir a un álbum",
    "Rename…": "Cambiar nombre…",
    "New Album Here…": "Nuevo álbum aquí…",
    "New Folder Here…": "Nueva carpeta aquí…",
    "Move Out of “{folder}”": "Sacar de “{folder}”",
    "Move To…": "Mover a…",
    "Move “{name}” To": "Mover “{name}” a",
    "Move {count} Item To": ("Mover {count} elemento a", "Mover {count} elementos a"),
    "Choose a folder.": "Elige una carpeta.",
    "Here now": "Está aquí",
    "Move": "Mover",
    "Moved to Top Level": "Movido al nivel principal",
    "Moved to “{folder}”": "Movido a “{folder}”",
    "Delete Folder…": "Eliminar carpeta…",
    "Delete Album…": "Eliminar álbum…",
    "Rename Folder": "Cambiar nombre de la carpeta",
    "Rename Album": "Cambiar nombre del álbum",
    "Delete “{name}”?": "¿Eliminar “{name}”?",
    "This deletes the folder and the albums and folders inside it. Your photos are not deleted.":
        "Esto elimina la carpeta y los álbumes y carpetas que tiene dentro. Tus fotos no se borran.",
    "Delete": "Eliminar",
    "This deletes the album. Your photos are not deleted.": "Esto elimina el álbum. Tus fotos no se borran.",
    "New Folder": "Nueva carpeta",
    "Give the folder a name.": "Ponle un nombre a la carpeta.",
    "Folder name": "Nombre de la carpeta",
    "Create": "Crear",
    "Untitled Folder": "Carpeta sin nombre",
    "Edit Smart Album…": "Editar álbum inteligente…",
    "Delete Smart Album…": "Eliminar álbum inteligente…",
    "This deletes the smart album. Your photos are not deleted.": "Esto elimina el álbum inteligente. Tus fotos no se borran.",
    "New Album": "Nuevo álbum",
    "Give the album a name.": "Ponle un nombre al álbum.",
    "Album name": "Nombre del álbum",
    "Untitled Album": "Álbum sin nombre",
    "Unhide": "Mostrar",
    "Unhide {count} Photos": "Mostrar {count} fotos",
    "Hide": "Ocultar",
    "Hide {count} Photos": "Ocultar {count} fotos",
    "Export {count} Photos…": "Exportar {count} fotos…",
    "Delete {count} Photos": "Eliminar {count} fotos",
    "Open": "Abrir",
    "Remove from Favourites": "Quitar de favoritos",
    "Open a Piklin Library": "Abrir una biblioteca de Piklin",
    "Not a Piklin Library": "No es una biblioteca de Piklin",
    "“{name}” is not a Piklin library. Choose a library, such as “Piklin Library.piklin”.":
        "“{name}” no es una biblioteca de Piklin. Elige una biblioteca, como “Piklin Library.piklin”.",
    "Choose a Folder with Photos": "Elige una carpeta con fotos",
    "Looking for photos…": "Buscando fotos…",
    "Looking for photos": "Buscando fotos",
    "Reading photo details": "Leyendo los datos de las fotos",
    "Preparing previews": "Preparando vistas previas",
    "{count} new": "{count} nuevas",
    "Piklin can back up your photos and videos to a drive, a NAS or a cloud service. Once one is connected, new photos, videos and edits are copied there automatically.\n\nNothing leaves your computer unless you choose where.":
        "Piklin puede hacer una copia de tus fotos y videos en una unidad, un NAS o un servicio en la nube. Cuando conectes uno, las fotos, videos y cambios nuevos se copiarán allí automáticamente.\n\nNada sale de tu ordenador a menos que elijas dónde.",
    "Not Now": "Ahora no",
    "NAS or WebDAV Server": "NAS o servidor WebDAV",
    "Welcome to Piklin": "Te damos la bienvenida a Piklin",
    "Choose a folder with your photos and Piklin will organize them.\n\nYour photos are never moved or changed. Edits are saved separately, so your originals stay exactly as they are.":
        "Elige una carpeta con tus fotos y Piklin las organizará.\n\nTus fotos nunca se mueven ni se modifican. Los cambios se guardan aparte, así que tus originales se quedan tal cual.",
    "Use {folder}": "Usar {folder}",
    "Choose Folder…": "Elegir carpeta…",
    "© 2026 Vezzu Studio. All rights reserved.": "© 2026 Vezzu Studio. Todos los derechos reservados.",
    "Piklin was created by Vezzu Studio.\n\nA photo and video library and editor for Linux. {tools} editing tools · {formats} file formats · everything runs on this computer.":
        "Piklin fue creado por Vezzu Studio.\n\nUna biblioteca y editor de fotos y videos para Linux. {tools} herramientas de edición · {formats} formatos de archivo · todo funciona en este ordenador.",
    "Piklin is free to use under the Piklin License 1.0. © 2026 Vezzu Studio.\n\nYou may install and use Piklin on as many of your own computers as you like, at home or for work, including commercial use. You may not modify, redistribute or sell it.\n\nYour photos, edits and everything you make with Piklin are yours.":
        "Piklin es de uso gratuito bajo la Licencia de Piklin 1.0. © 2026 Vezzu Studio.\n\nPuedes instalar y usar Piklin en todos tus ordenadores, en casa o en el trabajo, incluido el uso comercial. No puedes modificarlo, redistribuirlo ni venderlo.\n\nTus fotos, tus cambios y todo lo que hagas con Piklin son tuyos.",
    "Inter typeface": "Tipografía Inter",
    "Photos Are Still Being Copied": "Todavía se están copiando fotos",
    "If you close Piklin now, the copy stops. The photos already copied stay in your library.":
        "Si cierras Piklin ahora, la copia se detiene. Las fotos ya copiadas se quedan en tu biblioteca.",
    "Keep Copying": "Seguir copiando",
    "Stop and Close": "Detener y cerrar",

    "Make Album Cover": "Usar como portada del álbum",
    "Delete {count} Album…": ("Eliminar {count} álbum…", "Eliminar {count} álbumes…"),
    "Delete {count} album?": ("¿Eliminar {count} álbum?", "¿Eliminar {count} álbumes?"),
    "This deletes the albums. Your photos are not deleted.": "Esto elimina los álbumes. Tus fotos no se borran.",
    "Every hour, Piklin asks GitHub whether a new version is out, installs it by itself and reopens. Nothing about you or your photos is sent.":
        "Cada hora, Piklin pregunta a GitHub si hay una versión nueva, la instala sola y se vuelve a abrir. No se envía nada sobre ti ni sobre tus fotos.",
    "Smaller files save space. Videos are copied first and made smaller afterwards, in the background. Keep the originals if you want the best quality for editing later.":
        "Los archivos más pequeños ahorran espacio. Los videos se copian primero y se reducen después, en segundo plano. Guarda los originales si quieres la mejor calidad para editar más tarde.",
    "Making videos smaller — {done} of {total} ({percent}%)": "Reduciendo videos — {done} de {total} ({percent}%)",
    "Back to {folder}": "Volver a {folder}",
    "For photos copied into the library: from a camera, a memory card, a USB drive or dragged in. Your folders are never changed.":
        "Para las fotos que se copian a la biblioteca: desde una cámara, una tarjeta de memoria, una unidad USB o arrastradas. Tus carpetas nunca se modifican.",
    "{count} identical copy": ("{count} copia idéntica", "{count} copias idénticas"),
    "Keep One of Each": "Dejar una de cada",
    "Remove {count} Extra Copy": ("Quitar {count} copia de más", "Quitar {count} copias de más"),
    "Each group below is the same photo more than once. Keep One of Each keeps the best copy of every group - the favourite, edited or in albums - and moves the extra copies to Recently Deleted, where they stay for 30 days. Select some groups to do it for just those.":
        "Cada grupo de abajo es la misma foto repetida. Dejar una de cada se queda con la mejor copia de cada grupo (la favorita, la editada o la que está en álbumes) y manda las copias de más a Eliminados recientemente, donde se quedan 30 días. Selecciona algunos grupos para hacerlo solo con esos.",
    "Album cover changed": "Portada del álbum cambiada",

    # -- updates -------------------------------------------------------------------------------
    "Piklin {version} is available. Installing it…": "Piklin {version} está disponible. Instalándola…",
    "Piklin {version} is installed. Piklin will reopen in a moment.":
        "Piklin {version} está instalada. Piklin se volverá a abrir en un momento.",
    "Piklin {version} couldn't be installed automatically.":
        "No se pudo instalar Piklin {version} automáticamente.",
    "Keep Piklin up to date": "Mantener Piklin actualizado",
    "Once a day, Piklin asks GitHub whether a new version is out, installs it by itself and reopens. Nothing about you or your photos is sent.":
        "Una vez al día, Piklin pregunta a GitHub si hay una versión nueva, la instala sola y se vuelve a abrir. No se envía nada sobre ti ni sobre tus fotos.",

    # -- help ----------------------------------------------------------------------------------
    "Help": "Ayuda",
    "How to Use Piklin": "Cómo usar Piklin",
    "What each button does, in a few words. Open this guide at any time from Help in the menu, or press F1.":
        "Lo que hace cada botón, en pocas palabras. Abre esta guía cuando quieras desde Ayuda en el menú, o pulsa F1.",
    "Getting Started": "Primeros pasos",
    "Add your photos": "Añade tus fotos",
    "Open the menu ⋮ at the top of the sidebar and choose Add Folder… Your photos stay where they are: Piklin only shows them.":
        "Abre el menú ⋮ arriba de la barra lateral y elige Añadir carpeta… Tus fotos se quedan donde están: Piklin solo las muestra.",
    "Bring in photos from a camera or USB drive": "Trae fotos de una cámara o una unidad USB",
    "Connect it and it appears under Devices in the sidebar. Choose the photos you want and press Import.":
        "Conéctala y aparece en Dispositivos, en la barra lateral. Elige las fotos que quieras y pulsa Importar.",
    "Drag and drop": "Arrastrar y soltar",
    "Drag photos from your files onto Piklin to add them, or onto an album in the sidebar to put them straight into that album.":
        "Arrastra fotos desde tus archivos a Piklin para añadirlas, o a un álbum de la barra lateral para ponerlas directamente en ese álbum.",
    "Moving Around": "Cómo moverte",
    "Years, Months, Days, All Photos": "Años, Meses, Días, Todas las fotos",
    "The buttons at the top change how your photos are grouped.": "Los botones de arriba cambian cómo se agrupan tus fotos.",
    "Move the slider at the top left to make the photos bigger or smaller.":
        "Mueve el control deslizante de arriba a la izquierda para ver las fotos más grandes o más pequeñas.",
    "Whole photos or squares": "Fotos completas o cuadradas",
    "The button next to the slider shows each photo whole instead of cut to a square.":
        "El botón junto al control deslizante muestra cada foto completa en vez de recortada en cuadrado.",
    "Search": "Buscar",
    "Type in the search box to find photos by name, date, month, camera or keywords. Ctrl+F":
        "Escribe en la caja de búsqueda para encontrar fotos por nombre, fecha, mes, cámara o palabras clave. Ctrl+F",
    "Show only favourites, videos, edited photos, photos with a location and more. Show All brings everything back.":
        "Muestra solo favoritos, videos, fotos editadas, fotos con ubicación y más. Mostrar todo vuelve a enseñarlo todo.",
    "Choosing Photos": "Elegir fotos",
    "Choose a photo": "Elegir una foto",
    "Click a photo once. A green check shows it is chosen. Click it again to let it go.":
        "Haz clic una vez en una foto. Una marca verde indica que está elegida. Vuelve a hacer clic para soltarla.",
    "Choose several": "Elegir varias",
    "Hold Ctrl and click each photo, or hold Shift to choose everything between two photos. Ctrl+A chooses them all.":
        "Mantén Ctrl y haz clic en cada foto, o mantén Mayús para elegir todo lo que hay entre dos fotos. Ctrl+A las elige todas.",
    "Open a photo": "Abrir una foto",
    "Double-click a photo to see it big. Press Esc to go back.": "Haz doble clic en una foto para verla en grande. Pulsa Esc para volver.",
    "More options": "Más opciones",
    "Right-click a photo to see everything you can do with it.": "Haz clic derecho en una foto para ver todo lo que puedes hacer con ella.",
    "The Bar for Chosen Photos": "La barra de las fotos elegidas",
    "Marks the chosen photos as favourites, so they appear in Favourites. Key: F":
        "Marca las fotos elegidas como favoritas, para que aparezcan en Favoritos. Tecla: F",
    "The photos wait there for 30 days, so you can still get them back. Key: Delete":
        "Las fotos esperan ahí 30 días, así que todavía puedes recuperarlas. Tecla: Supr",
    "Saves copies of the chosen photos in a folder you pick, to share or print them. Ctrl+E":
        "Guarda copias de las fotos elegidas en la carpeta que elijas, para compartirlas o imprimirlas. Ctrl+E",
    "Puts the chosen photos into an album.": "Pone las fotos elegidas en un álbum.",
    "Turns the chosen photos right or left. Ctrl+R turns right, Ctrl+Shift+R turns left.":
        "Gira las fotos elegidas a la derecha o a la izquierda. Ctrl+R gira a la derecha, Ctrl+Mayús+R a la izquierda.",
    "Looking at One Photo": "Viendo una foto",
    "Returns to your photos. Key: Esc": "Vuelve a tus fotos. Tecla: Esc",
    "Previous and Next": "Anterior y siguiente",
    "Moves to the photo before or after this one.": "Pasa a la foto anterior o a la siguiente.",
    "Turns the photo. You can turn it back at any time.": "Gira la foto. Puedes volver a girarla cuando quieras.",
    "Marks this photo as a favourite. Key: F": "Marca esta foto como favorita. Tecla: F",
    "Full Screen": "Pantalla completa",
    "Shows the photo on the whole screen. Key: F11": "Muestra la foto en toda la pantalla. Tecla: F11",
    "Info": "Información",
    "Shows the date, camera, size and place, and lets you add a title or keywords. Ctrl+I":
        "Muestra la fecha, la cámara, el tamaño y el lugar, y te deja añadir un título o palabras clave. Ctrl+I",
    "Opens the editing tools. Key: Enter": "Abre las herramientas de edición. Tecla: Intro",
    "Editing": "Editar",
    "Your original is always safe": "Tu original siempre está a salvo",
    "Edits are kept separately. Remove All Edits brings the photo back exactly as it was.":
        "Los cambios se guardan aparte. Quitar todos los cambios deja la foto exactamente como estaba.",
    "Undo and redo": "Deshacer y rehacer",
    "Ctrl+Z undoes the last change and Ctrl+Shift+Z brings it back.":
        "Ctrl+Z deshace el último cambio y Ctrl+Mayús+Z lo vuelve a poner.",
    "Compare with the original": "Comparar con el original",
    "Hold the M key to see the photo without your edits.": "Mantén pulsada la tecla M para ver la foto sin tus cambios.",
    "Albums and the Sidebar": "Álbumes y barra lateral",
    "New album or folder": "Nuevo álbum o carpeta",
    "Press + next to Albums. A folder keeps several albums together.":
        "Pulsa + junto a Álbumes. Una carpeta reúne varios álbumes.",
    "Open a folder": "Abrir una carpeta",
    "Click a folder to see its albums as cards, then click one to open it.":
        "Haz clic en una carpeta para ver sus álbumes como tarjetas, y luego haz clic en uno para abrirlo.",
    "Photos you hide with Ctrl+L leave your library and wait here.":
        "Las fotos que ocultas con Ctrl+L salen de tu biblioteca y esperan aquí.",
    "Finds photos that are exact copies, so you can keep just one.":
        "Encuentra las fotos que son copias exactas, para que te quedes solo con una.",
    "Get deleted photos back within 30 days.": "Recupera las fotos eliminadas durante 30 días.",
    "Keeping Your Photos Safe": "Proteger tus fotos",
    "Backups": "Copias de seguridad",
    "Open the menu ⋮ and choose Backups… to keep a copy on a drive, a NAS or a cloud service. New photos are copied there automatically.":
        "Abre el menú ⋮ y elige Copias de seguridad… para guardar una copia en una unidad, un NAS o un servicio en la nube. Las fotos nuevas se copian allí automáticamente.",
    "Change the language, the look, and how photos are brought in. Ctrl+,":
        "Cambia el idioma, el aspecto y cómo entran las fotos. Ctrl+,",

    # -- video export ----------------------------------------------------------------------------
    "MP4 (H.264)": "MP4 (H.264)",
    "WebM (VP9)": "WebM (VP9)",
    "Animated GIF": "GIF animado",
    "Nothing is left to export: the whole video is cut out.": "No queda nada que exportar: se cortó todo el video.",
    "{format} can't be created on this computer.": "No se puede crear {format} en este ordenador.",
    "A GIF can be at most {limit} seconds long; this one would be {length}.":
        "Un GIF puede durar como máximo {limit} segundos; este duraría {length}.",
    "No frames to put in the GIF.": "No hay fotogramas para el GIF.",
}


def _po_quote(text: str) -> str:
    text = text.replace("\\", "\\\\").replace('"', '\\"').replace("\t", "\\t")
    if "\n" in text:
        parts = text.split("\n")
        lines = [p + "\\n" for p in parts[:-1]] + ([parts[-1]] if parts[-1] else [])
        return '""\n' + "\n".join(f'"{l}"' for l in lines)
    return f'"{text}"'


def build(pot_path: str, po_path: str) -> None:
    """Write es.po for every entry in the template; report what is missing."""
    import re
    import string
    pot = open(pot_path, encoding="utf-8").read()
    blocks = pot.split("\n\n")
    header = (
        'msgid ""\nmsgstr ""\n'
        '"Project-Id-Version: Piklin\\n"\n'
        '"Language: es\\n"\n'
        '"Language-Team: Spanish\\n"\n'
        '"Last-Translator: Vezzu Studio\\n"\n'
        '"PO-Revision-Date: 2026-09-13 12:00+0000\\n"\n'
        '"MIME-Version: 1.0\\n"\n'
        '"Content-Type: text/plain; charset=UTF-8\\n"\n'
        '"Content-Transfer-Encoding: 8bit\\n"\n'
        '"Plural-Forms: nplurals=2; plural=(n != 1);\\n"\n')

    def unquote(chunk):
        parts = re.findall(r'"((?:[^"\\]|\\.)*)"', chunk)
        raw = "".join(parts)
        return (raw.replace('\\"', '"').replace("\\n", "\n").replace("\\t", "\t")
                .replace("\\\\", "\\"))

    def fields(text):
        return {f for _l, f, _s, _c in string.Formatter().parse(text) if f}

    out, missing, mismatched = [header], [], []
    for block in blocks[1:]:
        m_id = re.search(r'^msgid ((?:".*"\n?)+)', block, re.M)
        if not m_id:
            continue
        msgid = unquote(m_id.group(1))
        m_ctx = re.search(r'^msgctxt ((?:".*"\n?)+)', block, re.M)
        context = unquote(m_ctx.group(1)) if m_ctx else None
        m_pl = re.search(r'^msgid_plural ((?:".*"\n?)+)', block, re.M)
        comments = "\n".join(l for l in block.split("\n") if l.startswith("#"))
        # Piklin formats with str.format only; "% s" in "{percent}% strength"
        # is not a printf directive.
        comments = comments.replace("#, python-format, ", "#, ").replace("#, python-format\n", "")
        value = ES.get(f"{context}\x04{msgid}" if context else msgid)
        if value is None:
            missing.append(msgid)
        entry = (comments + "\n" if comments else "")
        if context:
            entry += f"msgctxt {_po_quote(context)}\n"
        entry += f"msgid {_po_quote(msgid)}\n"
        if m_pl:
            plural = unquote(m_pl.group(1))
            one, many = value if isinstance(value, tuple) else ("", "")
            entry += f"msgid_plural {_po_quote(plural)}\n"
            entry += f"msgstr[0] {_po_quote(one)}\nmsgstr[1] {_po_quote(many)}"
            for src, tr in ((msgid, one), (plural, many)):
                if tr and fields(src) != fields(tr) and not (src is msgid and fields(tr) <= fields(plural)):
                    mismatched.append((src, tr))
        else:
            tr = value if isinstance(value, str) else ""
            entry += f"msgstr {_po_quote(tr)}"
            if tr and fields(msgid) != fields(tr):
                mismatched.append((msgid, tr))
        out.append(entry)
    open(po_path, "w", encoding="utf-8").write("\n\n".join(out) + "\n")
    print(f"es.po: {len(out) - 1} entries, {len(missing)} missing, {len(mismatched)} placeholder mismatches")
    for m in missing:
        print("  missing:", repr(m)[:120])
    for src, tr in mismatched:
        print("  mismatch:", repr(src)[:60], "->", repr(tr)[:60])


if __name__ == "__main__":
    import os
    here = os.path.dirname(os.path.abspath(__file__))
    build(os.path.join(here, "piklin.pot"), os.path.join(here, "es.po"))
